resolver: https://raw.githubusercontent.com/input-output-hk/cardano-haskell/aaf316ac9c39466a6eccf53f2f3aabb5a266b62e/snapshots/cardano-1.21.1.yaml
compiler: ghc-8.6.5

#allow-newer: true

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
- .

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

extra-deps:
  - persistent-2.10.5.1
  - persistent-postgresql-2.10.1.2
  - persistent-template-2.8.2.3

  # This is something extra we need.
  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 9e498e0962044c582df0cbf2f81fa0450a67d5f7
    subdirs:
    - cardano-client
    # rm these when https://github.com/hasufell/stack2cabal/issues/30 is fixed
    - io-sim
    - io-sim-classes
    - network-mux
    - ntp-client
    - ouroboros-network
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-shelley
    - typed-protocols
    - typed-protocols-examples
    - ouroboros-network-framework
    - Win32-network

  - git: https://github.com/hasufell/cardano-db-sync
    commit: a5fad530877c33cd0ae5351a097a6761c002deb2
    subdirs:
      - cardano-db
      - cardano-db-sync
      - cardano-db-sync-extended

nix:
  shell-file: nix/stack-shell.nix
